#
#   请创建一个application.yml文件并将数据库xxxx部分替换成自己的内容
#
server:
  servlet:
    context-path: /api
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xxxx
    url: jdbc:mysql://xxxx:3306/db1?characterEncoding=utf-8&useSSL=true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.meeting.model.entity



